config/routes.rb
Rails.application.routes.draw do

  get '/courses/planilla_asistencia/' => 'courses#planilla_asistencia', as: :planilla_asistencia
  get '/courses/planilla_notas/' => 'courses#planilla_notas', as: :planilla_notas
  resources :courses
  root to: 'dashboard#index'

  get 'studens/planillas'

  get '/' => 'dashboard#index', as: :dashboard
  get 'estadosdecuenta' => 'dashboard#estados_de_cuenta', as: :estados_de_cuenta

  resources :payments do
    member do 
      get 'recibo' => 'payments#gen_comprobante'
    end
  end
  resources :entries
  resources :expendings
  resources :accounts
  resources :studies
  resources :students
  resources :cashes do 
    collection do 
      get 'today' => 'cashes#today', as: :today
    end
  end

  namespace :api do 
    resources :courses do 
      collection do 
        post 'registrarpago' => 'courses#registrar_pago'
      end
    end
    post 'cashes/setmi' => 'cashes#set_monto_inicial'
    post 'cashes/cerrar' => 'cashes#cerrar'
  end

end

app/models/student.rb
# == Schema Information
#
# Table name: students
#
#  id              :integer          not null, primary key
#  nombre_completo :string
#  dni             :string(15)
#  matricula       :integer
#  direccion       :string
#  comentarios     :text
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class Student < ActiveRecord::Base

  has_many :courses

  validates_presence_of :dni, :nombre_completo, :direccion


  def self.search(params)     
    if params[:mes_adeudado].present? || params[:carrers_ids].present?
      ids_con_deuda = Course.students_ids_con_deuda_en(params[:mes_adeudado], params[:carrers_ids])
      self.where(id: ids_con_deuda)
    else 
      self.all
    end
  end

  def to_s
    nombre_completo    
  end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.search(params).page(params[:page])
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:nombre_completo, :dni, :matricula, :direccion, :comentarios)
    end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<%= form_for(@student) do |f| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% @student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre_completo %><br>
    <%= f.text_field :nombre_completo %>
  </div>
  <div class="field">
    <%= f.label :dni %><br>
    <%= f.text_field :dni %>
  </div>
  <div class="field">
    <%= f.label :matricula %><br>
    <%= f.number_field :matricula %>
  </div>
  <div class="field">
    <%= f.label :direccion %><br>
    <%= f.text_field :direccion %>
  </div>
  <div class="field">
    <%= f.label :comentarios %><br>
    <%= f.text_area :comentarios %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form' %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-lg-12">
      <h1 class="page-header">Estudiantes</h1>
  </div>
  <!-- /.col-lg-12 -->
</div>

<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
        <div class="panel-heading">
            Listado de estudiantes
        </div>
        <!-- /.panel-heading -->
        <div class="panel-body">

        <%= bootstrap_form_tag url: '/students', method: :get do |f| %>
          <div class="row" style="margin-bottom:1em">
            <div class="col-md-4">
              <label for="account_id">Carreras</label>
              <%= select_tag("carrers_ids[]", "<option> </option>".html_safe + options_for_select(Study.carreras.pluck(:nombre, :id), params[:carrers_ids]), class: 'multiple', multiple: true) %>
            </div>
            <div class="col-md-4" >
              <label for="account_id">Cursos</label>
              <%= select_tag("carrers_ids[]", "<option> </option>".html_safe + options_for_select(Study.cursos.pluck(:nombre, :id), params[:carrers_ids]), class: 'multiple', multiple: true) %>
            </div>
            <div class="col-md-4" >
              <label for="account_id">Los que adeudan</label>
              <%= select_tag("periodo_adeudado", "<option>No filtrar</option>".html_safe + options_from_collection_for_select(Payment.periodos_actuales, :to_s, :to_s, params[:periodo_adeudado]), class: 'single') %>
            </div>
          </div>
          <%= f.submit("Filtrar") %>
        <% end %>
        <div style="margin-bottom:1em;margin-top:1em">
          <%= link_to 'Nuevo estudiante', new_student_path, class: 'btn btn-primary' %>
          
        </div>
        <%= paginate @students, :theme => 'twitter-bootstrap-3' %>

        <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
           <thead>
             <tr>
               <th>Nombre completo</th>
               <th>Dni</th>
               <th>Matricula</th>
               <th>Direccion</th>
               <th>Comentarios</th>
               <th>Pago</th>
               <th colspan="3"></th>
             </tr>
          </thead>

          <tbody>
            <% @students.each do |student| %>
              <tr class="odd gradeX">
                <td><%= student.nombre_completo %></td>
                <td><%= student.dni %></td>
                <td><%= student.matricula %></td>
                <td><%= student.direccion %></td>
                <td><%= truncate(student.comentarios, length: 40) %></td>
                <td><button class="btn btn-success">Registrar</button></td>
                <td>
                    <a href="<%= student_path(student) %>" class="btn glyphicon glyphicon-eye-open"></a>
                </td>
                <td><a href="<%= edit_student_path(student) %>" class="btn glyphicon glyphicon-edit"></a></td>
                <td><%= link_to '', student, method: :delete, data: { confirm: 'Estás seguro?' }, class: "btn glyphicon glyphicon-remove glyphicon glyphicon-plus" %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<%= link_to 'Nuevo estudiante', new_student_path, class: 'btn btn-primary' %>

<script>
  $( "select.multiple" ).select2({
    theme: "bootstrap",
    width: '100%',
    multiple: true
  });
  $("select.single").select2({
    theme: 'bootstrap',
    width: '100%'
  })
</script>

app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form' %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <ul class="nav nav-tabs">
      <li class="active">
        <a href="#datos" data-toggle="tab" aria-expanded="true">Datos</a>
      </li>
      <li>
        <a href="#cursado" data-toggle="tab" aria-expanded="true">Cursado</a>
      </li>
    </ul>
    <div class="tab-content">
      <div class="tab-pane fade active in" id="datos">
        <br>
        <p>
          <strong>Nombre completo:</strong>
          <%= @student.nombre_completo %>
        </p>

        <p>
          <strong>Dni:</strong>
          <%= @student.dni %>
        </p>

        <p>
          <strong>Matricula:</strong>
          <%= @student.matricula %>
        </p>

     
        <p>
          <strong>Direccion:</strong>
          <%= @student.direccion %>
        </p>

        <p>
          <strong>Comentarios:</strong>
          <%= @student.comentarios %>
        </p>

        <%= link_to 'Editar', edit_student_path(@student), class: 'btn btn-primary' %>    
        <%= link_to 'Atrás', students_path, class: 'btn btn-default' %>
 
      </div>
      <div class="tab-pane fade" id="cursado">
         <br>
         <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
            <thead>
              <tr>
                <th>Nombre curso</th>
                <th>Inicio</th>
              </tr>
            </thead>

            <tbody>
              <% @student.courses.each do |course| %>
                <tr class="odd gradeX">
                  <td><%= course.study.nombre %></td>
                  <td><%= course.anio_inicio %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
      </div>
    </div>
  </div>
</div>