config/routes.rb
Rails.application.routes.draw do

  get '/courses/planilla_asistencia/' => 'courses#planilla_asistencia', as: :planilla_asistencia
  get '/courses/planilla_notas/' => 'courses#planilla_notas', as: :planilla_notas
  resources :courses
  root to: 'dashboard#index'

  get 'studens/planillas'

  get '/' => 'dashboard#index', as: :dashboard
  get 'estadosdecuenta' => 'dashboard#estados_de_cuenta', as: :estados_de_cuenta

  resources :payments do
    member do 
      get 'recibo' => 'payments#gen_comprobante'
    end
  end
  resources :entries
  resources :expendings
  resources :accounts
  resources :studies
  resources :students
  resources :cashes do 
    collection do 
      get 'today' => 'cashes#today', as: :today
    end
  end

  namespace :api do 
    resources :courses do 
      collection do 
        post 'registrarpago' => 'courses#registrar_pago'
      end
    end
    post 'cashes/setmi' => 'cashes#set_monto_inicial'
    post 'cashes/cerrar' => 'cashes#cerrar'
  end

end

app/models/expending.rb
# == Schema Information
#
# Table name: expendings
#
#  id         :integer          not null, primary key
#  fecha      :date
#  monto      :decimal(, )
#  account_id :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Expending < ActiveRecord::Base

  belongs_to :account

  validates_presence_of :fecha, :monto, :account_id

  def self.search(params)
    start_date = params[:start_date] || 100.years.ago
    end_date   = params[:start_date] || Date.today + 1000.years

    expendings = Expending.where(fecha: start_date..end_date)

    expendings = expendings.where(account_id: params[:account_ids]) if params[:account_ids]
    expendings
  end
end

app/controllers/expendings_controller.rb
class ExpendingsController < ApplicationController
  before_action :set_expending, only: [:show, :edit, :update, :destroy]

  def index
    @expendings = Expending.search(params)
  end

  def show
  end

  def new
    @expending = Expending.new
  end

  def edit
  end

  def create
    @expending = Expending.new(expending_params)

    respond_to do |format|
      if @expending.save
        format.html { redirect_to expendings_path, notice: 'Expending was successfully created.' }
      else
        format.html { render :new }
        format.json { render json: @expending.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @expending.update(expending_params)
        format.html { redirect_to @expending, notice: 'Expending was successfully updated.' }
        format.json { render :show, status: :ok, location: @expending }
      else
        format.html { render :edit }
        format.json { render json: @expending.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @expending.destroy
    respond_to do |format|
      format.html { redirect_to expendings_url, notice: 'Expending was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_expending
      @expending = Expending.find(params[:id])
    end

    def expending_params
      params.require(:expending).permit(:fecha, :monto, :account_id)
    end
end

app/helpers/expendings_helper.rb
module ExpendingsHelper
end

app/views/expendings/_form.html.erb
<%= bootstrap_form_for(@expending) do |f| %>
  <% if @expending.persisted? %>
    <%= f.text_field :id, label: 'Gasto nro', disabled: true %>
  <% end %>
  <%= f.date_field :fecha, value: (Date.today if @expending.new_record? )  %>
  <%= f.text_field :monto %>
  <%= f.select :account_id, options_from_collection_for_select(Account.de_gastos, :id, :nombre), label: 'Cuenta' %>
  <div class="form-inline">
    <%= f.submit 'Guardar', class: 'btn btn-primary' %>
    <%= link_to 'Atrás', expendings_path, class: 'btn btn-default pull-right' %>
  </div>
<% end %>

<script>
  $( "select" ).select2({
    theme: "bootstrap",
    width: '100%',
  });
</script>

app/views/expendings/edit.html.erb
<h1>Editando gasto</h1>

<%= render 'form' %>

app/views/expendings/index.html.erb
<div class="row">
  <div class="col-lg-12">
      <h1 class="page-header">Gastos</h1>
  </div>
  <!-- /.col-lg-12 -->
</div>

<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
        <div class="panel-heading">
            Listado de gastos
        </div>
        <!-- /.panel-heading -->
        <div class="panel-body">

        <div class="row" style="margin-bottom:2em">
          <%= bootstrap_form_tag url: '/expendings', method: :get do |f| %>
            <div class="col-md-12">
              <label for="account_id">Cuentas</label>
              <%= select_tag("account_ids[]", "<option> </option>".html_safe + options_from_collection_for_select(Account.de_gastos, :id, :nombre, params[:account_ids]), multiple: true) %>
            </div>
            <div class="col-md-12" style="margin-top:2em">
              <div class="col-md-6" style="padding-left:0px">
                <%= f.date_field(:start_date, value: params[:start_date]) %>
              </div>
              <div class="col-md-6" style="padding-left:0px">
                <%= f.date_field(:end_date, label: "Fecha fin", value: params[:end_date]) %>
              </div>
            <%= f.submit("Filtrar") %>
            </div>
          <% end %>
        </div>

       <table style="margin-top:1em" width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
          <thead>
            <tr>
              <th>Gasto nro</th>
              <th>Fecha</th>
              <th>Monto</th>
              <th>Cuenta</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @expendings.each do |expending| %>
              <tr class="odd gradeX">
                <td><%= expending.id %></td>
                <td><%= expending.fecha %></td>
                <td><%= expending.monto %></td>
                <td><%= expending.account %></td>
                <td><a href="<%= edit_expending_path(expending) %>" class="btn glyphicon glyphicon-edit"></a></td>
                <td><%= link_to '', expending, method: :delete, data: { confirm: 'Estás seguro?' }, class: "btn glyphicon glyphicon-remove glyphicon glyphicon-plus" %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<%= link_to 'Nuevo gasto', new_expending_path, class: 'btn btn-primary' %>

<script>
  $( "select" ).select2({
    theme: "bootstrap",
    width: '100%',
    multiple: true
  });
</script>

app/views/expendings/new.html.erb
<h1>Nuevo gasto</h1>

<%= render 'form' %>

app/views/expendings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fecha:</strong>
  <%= @expending.fecha %>
</p>

<p>
  <strong>Monto:</strong>
  <%= @expending.monto %>
</p>

<p>
  <strong>Cuenta:</strong>
  <%= @expending.account %>
</p>

<%= link_to 'Editar', edit_expending_path(@expending) %> 
<br>
<%= link_to 'Atrás', expendings_path %>