config/routes.rb
Rails.application.routes.draw do

  get '/courses/planilla_asistencia/' => 'courses#planilla_asistencia', as: :planilla_asistencia
  get '/courses/planilla_notas/' => 'courses#planilla_notas', as: :planilla_notas
  resources :courses
  root to: 'dashboard#index'

  get 'studens/planillas'

  get '/' => 'dashboard#index', as: :dashboard
  get 'estadosdecuenta' => 'dashboard#estados_de_cuenta', as: :estados_de_cuenta

  resources :payments do
    member do 
      get 'recibo' => 'payments#gen_comprobante'
    end
  end
  resources :entries
  resources :expendings
  resources :accounts
  resources :studies
  resources :students
  resources :cashes do 
    collection do 
      get 'today' => 'cashes#today', as: :today
    end
  end

  namespace :api do 
    resources :courses do 
      collection do 
        post 'registrarpago' => 'courses#registrar_pago'
      end
    end
    post 'cashes/setmi' => 'cashes#set_monto_inicial'
    post 'cashes/cerrar' => 'cashes#cerrar'
  end

end

app/models/study.rb
# == Schema Information
#
# Table name: studies
#
#  id           :integer          not null, primary key
#  nombre       :string(100)
#  descripcion  :string
#  tipo_estudio :string(20)
#  duracion     :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  monto_cuota  :decimal(, )      not null
#  requisitos   :text
#

class Study < ActiveRecord::Base

    
  has_many :study_expending_accounts
  has_many :cuentas_de_gastos, through: :study_expending_accounts, source: :account

  accepts_nested_attributes_for :cuentas_de_gastos

  CARRERA = "CARRERA"
  CURSO = "CURSO"

  TIPOS_ESTUDIO = [CARRERA, CURSO]

  validates_inclusion_of :tipo_estudio, :in => TIPOS_ESTUDIO, :on => :create, :message => "El tipo debe ser CARRERA  o CURSO"
  
  REQUISITOS_DISPONIBLES = %w{fotos DNI partida_de_nacimiento titulo_secundario certificado_buena_salud grupo_sanguineo}

  serialize :requisitos
  validates_presence_of :monto_cuota

  def self.carreras
    self.where(tipo_estudio: CARRERA).order(nombre: :asc)
  end

  def self.cursos
    self.where(tipo_estudio: CURSO).order(nombre: :asc)
  end

  def self.meses
    (1..12).map { |n|
      [n, I18n.l(Date.new(Date.today.year, n, 1), format: "%B").capitalize] 
    }
  end

  def es_requisito? req
    requisitos.include? req if requisitos
  end

  def duracion_to_s
    
  end

  def carrera?
    tipo_estudio == CARRERA
  end

  def curso?
    !carrera?    
  end

  def to_s
    nombre
  end

  def ingresos_anio(anio_inicio = nil, **params)
    params[:inicio] = (Date.today - 1000.years).to_s if params[:inicio].present? == false
    params[:fin]    = (Date.today + 1000.years).to_s if params[:fin].present? == false

    if anio_inicio
      Payment.includes(:course => :study)
             .where(courses: {anio_inicio: anio_inicio, study_id: self.id})
             .where(fecha: params[:inicio]..params[:fin])
             .sum('payments.monto')
    else 
      Payment.includes(:course => :study)
             .where(courses: {study_id: self.id})
             .where(fecha: params[:inicio]..params[:fin])
             .sum('payments.monto')
    end
  end

  def sumar_gastos(**params)
    params[:inicio] = (Date.today - 1000.years).to_s if params[:inicio].present? == false
    params[:fin]    = (Date.today + 1000.years).to_s if params[:fin].present? == false

    if params[:cuenta].present?
      Expending.where(account: params[:cuenta], fecha: params[:inicio]..params[:fin]).sum(:monto)
    else
      Expending.where(fecha: params[:inicio]..params[:fin], account: cuentas_de_gastos).sum(:monto)
    end
  end

  def balance(**params)
    ingresos_anio(params) - sumar_gastos(params)
  end

  def gastos_entre(inicio, fin)
    if inicio.present? == false 
      inicio = Date.today - 1000.years
      inicio = inicio.to_s
    end
    if fin.present? == false
      fin = Date.today + 1000.years
      fin = fin.to_s
    end
    Expending.where(account_id: cuentas_de_gastos.pluck(:id), fecha: inicio..fin)
  end
end

app/controllers/studies_controller.rb
class StudiesController < ApplicationController
  before_action :set_study, only: [:show, :edit, :update, :destroy]

  # GET /studies
  # GET /studies.json
  def index
    @studies = Study.all
  end

  # GET /studies/1
  # GET /studies/1.json
  def show
  end

  # GET /studies/new
  def new
    @study = Study.new
  end

  # GET /studies/1/edit
  def edit
  end

  # POST /studies
  # POST /studies.json
  def create
    @study = Study.new(study_params)

    respond_to do |format|
      if @study.save
        format.html { redirect_to studies_path, notice: 'Study was successfully created.' }
        format.json { render :show, status: :created, location: @study }
      else
        format.html { render :new }
        format.json { render json: @study.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /studies/1
  # PATCH/PUT /studies/1.json
  def update
    respond_to do |format|
      if @study.update(study_params)
        format.html { redirect_to studies_path, notice: 'Study was successfully updated.' }
        format.json { render :show, status: :ok, location: @study }
      else
        format.html { render :edit }
        format.json { render json: @study.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /studies/1
  # DELETE /studies/1.json
  def destroy
    @study.destroy
    respond_to do |format|
      format.html { redirect_to studies_url, notice: 'Study was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_study
      @study = Study.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def study_params
      params.require(:study).permit(:nombre, :descripcion, :tipo_estudio, :duracion, :monto_cuota, :requisitos => [], cuentas_de_gasto_ids: [])
    end
end

app/helpers/studies_helper.rb
module StudiesHelper
end

app/views/studies/_form.html.erb
<%= bootstrap_form_for(@study) do |f| %>
    <%= f.text_field :nombre %>
    <%= f.text_field :descripcion %>
    <%= f.select :tipo_estudio, options_from_collection_for_select(Study::TIPOS_ESTUDIO, :to_s, :to_s, @study.tipo_estudio) %>
    <%= f.number_field :monto_cuota, step: :any %>
    
    <label for="study[cuentas_de_gasto][]">Cuenta a la que imputar los gastos</label>
    <%= select_tag 'study[cuentas_de_gasto_ids][]', options_from_collection_for_select(Account.de_gastos_no_de_carrera + @study.cuentas_de_gastos, :id, :nombre, @study.cuentas_de_gastos.pluck(:id)), multiple: true %>
    
    <div class="form-group">
        <label for="">Requisitos</label>
        <% Study::REQUISITOS_DISPONIBLES.each do |req| %>    
            <div class="checkbox">
                <label  for="<%= req %>">
                <input type="checkbox" name="study[requisitos][]" value="<%= req %>" <%= "checked" if @study.es_requisito? req %> ><%= req.capitalize.humanize.capitalize %>
                </label>
            </div>
        <% end %>
    </div>
    <div class="form-inline">
        <%= f.submit "Guardar", class: 'btn btn-primary' %>
        <%= link_to 'Back', studies_path, class: 'btn btn-default pull-right' %>
    </div>
<% end %>

<script>
  $( "#study_tipo_estudio" ).select2({
    theme: "bootstrap",
    width: '100%'  
  });

  $( "#study_cuentas_de_gasto_ids_" ).select2({
    theme: "bootstrap",
    width: '100%'  , 
    multiple: true
  });
</script>

app/views/studies/edit.html.erb
<h1>Editando curso/carrera</h1>

<%= render 'form' %>

app/views/studies/index.html.erb
<div class="row">
  <div class="col-lg-12">
      <h1 class="page-header">Carreras y cursos</h1>
  </div>
  <!-- /.col-lg-12 -->
</div>

<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="panel-heading">
          Listado de estudios
      </div>
      <div class="panel-body">

        <table style="margin-top:1em" width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
          <thead>
            <tr>
              <th>Nombre</th>
              <th>Descripcion</th>
              <th>Tipo estudio</th>
              <th>Duracion</th>
              <th></th>
              <th></th>
              <th></th>
            </tr>
        </thead>

        <tbody>
          <% @studies.each do |study| %>
            <tr>
              <td><%= study.nombre %></td>
              <td><%= truncate(study.descripcion, length: 40) %></td>
              <td><%= study.tipo_estudio %></td>
              <td><%= study.duracion_to_s %></td>
               <td>
                    <a href="<%= study_path(study) %>" class="btn glyphicon glyphicon-eye-open"></a>
                </td>
                <td><a href="<%= edit_study_path(study) %>" class="btn glyphicon glyphicon-edit"></a></td>
                <td><%= link_to '', study, method: :delete, data: { confirm: 'Estás seguro?' }, class: "btn glyphicon glyphicon-remove glyphicon glyphicon-plus" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<br>

<%= link_to 'Nuevo estudio', new_study_path, class: 'btn btn-primary' %>

app/views/studies/new.html.erb
<h1>Nuevo estudio</h1>

<%= render 'form' %>

<br>

<%= link_to 'Back', studies_path, class: 'btn btn-default' %>

app/views/studies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @study.nombre %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @study.descripcion %>
</p>

<p>
  <strong>Tipo estudio:</strong>
  <%= @study.tipo_estudio %>
</p>

<p>
  <strong>Duracion:</strong>
  <%= @study.duracion %>
</p>

<%= link_to 'Edit', edit_study_path(@study) %> |
<%= link_to 'Back', studies_path %>