config/routes.rb
Rails.application.routes.draw do

  get '/courses/planilla_asistencia/' => 'courses#planilla_asistencia', as: :planilla_asistencia
  get '/courses/planilla_notas/' => 'courses#planilla_notas', as: :planilla_notas
  resources :courses
  root to: 'dashboard#index'

  get 'studens/planillas'

  get '/' => 'dashboard#index', as: :dashboard
  get 'estadosdecuenta' => 'dashboard#estados_de_cuenta', as: :estados_de_cuenta

  resources :payments do
    member do 
      get 'recibo' => 'payments#gen_comprobante'
    end
  end
  resources :entries
  resources :expendings
  resources :accounts
  resources :studies
  resources :students
  resources :cashes do 
    collection do 
      get 'today' => 'cashes#today', as: :today
    end
  end

  namespace :api do 
    resources :courses do 
      collection do 
        post 'registrarpago' => 'courses#registrar_pago'
      end
    end
    post 'cashes/setmi' => 'cashes#set_monto_inicial'
    post 'cashes/cerrar' => 'cashes#cerrar'
  end

end

app/models/account.rb
# == Schema Information
#
# Table name: accounts
#
#  id         :integer          not null, primary key
#  nombre     :string
#  tipo       :string(15)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Account < ActiveRecord::Base

  GASTO   = 'GASTO'
  INGRESO = 'INGRESO'

  TIPOS = [GASTO, INGRESO]

  def self.de_gastos
    self.where(tipo: GASTO)
  end

  def self.de_gastos_no_de_carrera
    self.de_gastos.where.not(id: StudyExpendingAccount.pluck(:account_id))
  end

  def self.de_ingresos
    self.where(tipo: INGRESO)
  end

  def to_s
    nombre
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]

  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to accounts_url, notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to accounts_url, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:nombre, :tipo)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_form.html.erb
<%= bootstrap_form_for(@account) do |f| %>
  <%= f.text_field :nombre %>
  <%= f.select :tipo, options_from_collection_for_select(Account::TIPOS, :to_s, :to_s, @account.tipo) %>
  <div class="form-inline">
    <%= f.submit 'Guardar', class: 'btn btn-primary' %>
    <%= link_to 'Atrás', accounts_path, class: 'btn btn-default pull-right' %>
    
  </div>
<% end %>

app/views/accounts/edit.html.erb
<h1>Editar cuenta</h1>

<%= render 'form' %>

<br>
<%= link_to 'Átrás', accounts_path, class: 'btn btn-default' %>

app/views/accounts/index.html.erb
<div class="row">
  <div class="col-lg-12">
      <h1 class="page-header">Cuentas</h1>
  </div>
  <!-- /.col-lg-12 -->
</div>


<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="panel-heading">
          Listado de cuentas
      </div>
      <div class="panel-body">
        <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
          <thead>
            <tr>
              <th>Nombre</th>
              <th>Tipo</th>
              <th></th>
              <th></th>
            </tr>
          </thead>

          <tbody>
            <% @accounts.each do |account| %>
              <tr>
                <td><%= account.nombre %></td>
                <td><%= account.tipo %></td>
                <td><a href="<%= edit_account_path(account) %>" class="btn glyphicon glyphicon-edit"></a></td>
                <td><%= link_to '', account, method: :delete, data: { confirm: 'Estás seguro?' }, class: "btn glyphicon glyphicon-remove glyphicon glyphicon-plus" %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
<br>

<%= link_to 'Nueva cuenta', new_account_path , class: 'btn btn-primary' %>

app/views/accounts/new.html.erb
<h1>Nueva cuenta</h1>

<%= render 'form' %>

app/views/accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @account.nombre %>
</p>

<p>
  <strong>Tipo:</strong>
  <%= @account.tipo %>
</p>

<%= link_to 'Edit', edit_account_path(@account) %> |
<%= link_to 'Back', accounts_path %>